version: '3'
services:
  k8s-aws-detox:
    build:
      context: .
      args:
        - KUBE_VERSION
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - KUBE_SERVER
      - KUBE_CA
      - KUBE_TOKEN
      - MAX_AGE
      - MAX_NODES_COUNT
      - CHECK_PERIOD
      - DRY_RUN
      - DRAIN
      - KUBERNETES_SERVICE_HOST
      - KUBERNETES_SERVICE_PORT_HTTPS
    entrypoint: k8s-aws-detox
